# Admin

## Gig
gig_admin:
    resource: routing/gig_admin.yaml
    prefix: /admin

## Homepage
homepage_admin:
    resource: routing/homepage_admin.yaml
    prefix: /admin

## Location
location_admin:
    resource: routing/location_admin.yaml
    prefix: /admin

## Login
secruity_admin:
    resource: routing/security_admin.yaml
    prefix: /admin

## News
news_admin:
    resource: routing/news_admin.yaml
    prefix: /admin

## Page
page_admin:
    resource: routing/page_admin.yaml
    prefix: /admin


# Frontend

## Gig
gig_frontend:
    resource: routing/gig_frontend.yaml

## News
news_frontend:
    resource: routing/news_frontend.yaml

## Page
page_frontend:
    resource: routing/page_frontend.yaml

